### ISSUE TITLE
New Features!

### ISSUE THREAD

**Issue by ghost** [lexi-lambda/SimpleJail#1]
Can you please add cells and guards to your plugin :D

**Comment by lexi-lambda** [comment]
Cells are currently low priority, though they may be implemented. Could you elaborate on them, though? For example, do you want a separate cell for each player? Separate named jails?

Also, could you explain what "guards" should be?

**Comment by ghost** [comment]
Well both ideas are from the original plugin Jail 2.0.5 which amazingly works pretty good with CB 1798.

Well I was thinking like a real cell and the amount how much players a cell can hold could be configurable in the config. So for example 2 players can fit in one cell. When there are already 2 players in one cell and a 3rd one is tried it will give an error like "This cell is already occupied" In Jail plugin the cell assignment is manual you can pick a random one but it doesnt say when the cell is already occupied and it kinda bugs out. Manual is actually good when you for example want to jail a player into a specific cell what has like a escape tunnel for survival maps or role plays. But in that case the message saying That cell is occupied is needed. Or there are other ways like making a command to see free cells and so on. 

Guards are angry wolves that spawn when a prisoner escapes, this makes total sence when you jail a player into a cell that has a secret tunnel to freedom. Jail 2.0.5 makes a cuboid around the jail like a worldedit seletion so if prisoners cross the border the wolves will come.

Thats pretty much what I had in mine.

Thanks

**Comment by lexi-lambda** [comment]
I am starting development on SimpleJailCells, and I'd love for you to take a look at [this thread](http://dev.bukkit.org/server-mods/simplejail/forum/31767-simple-jail-cells-development/) to give some more information on how it should be implemented. Thanks for your support!

**Comment by lexi-lambda** [comment]
Cells are now implemented in the form of the [SimpleJailCells extension](http://dev.bukkit.org/server-mods/simplejailcells/). I have no intention of implementing guards. This is now closed.
