### ISSUE TITLE
User stock in jail..

### ISSUE THREAD

**Issue by sky0matic** [lexi-lambda/SimpleJail#10]
Hi, there's a little problem. I did a test to jail someone on my server. The problem is that I can't unjail him ... When I try to the plugin says he's not in jail, but when I try to jail him, it says he is already in jail.

That messed up with everything like he can't connect to the server (using AuthMe) since it's written he couldn't use command while in jail.

What shoud I do ?

Already tried to delete the plugin files, but the same message is coming back ..

**Comment by lexi-lambda** [comment]
Can you please post the contents of the jailed.yml? Thank you.

**Comment by sky0matic** [comment]
It's empty..

**Comment by lexi-lambda** [comment]
Closed since this should be irrelevant with version 3.0.0.
