### ISSUE TITLE
Can't find permissions plugin...

### ISSUE THREAD

**Issue by ghost** [lexi-lambda/SimpleJail#3]
My console is outputting this. Simplejail can't find permissions plugin. I'm using bpermissions. Any idea what the problem is? I have configured a correct "jailed" group.

1:45:48))
13:06:37 [INFO] [AdminCmd] 92 extra help entries loaded from files: AdminCmd(92)

13:06:37 [INFO] [AdminCmd] bal_set has all his alias already registered. Command
 deactivated
13:06:37 [INFO] [AdminCmd] Disabled Alias(es) for bal_drop : d,
13:06:37 [INFO] [AdminCmd] Disabled Alias(es) for bal_vulcan : v,
13:06:37 [INFO] [AdminCmd] Disabled Alias(es) for bal_lockdown : lock,
13:06:37 [INFO] [AdminCmd] Disabled Alias(es) for bal_god : g,
13:06:37 [INFO] [AdminCmd] motd.txt loaded
13:06:37 [INFO] [AdminCmd] motdNewUser.txt loaded
13:06:37 [INFO] [AdminCmd] news.txt loaded
13:06:37 [INFO] [AdminCmd] rules.txt loaded
13:06:37 [INFO] [AdminCmd] 0 blacklisted items loaded.
13:06:37 [INFO] [AdminCmd] 0 blacklisted blocks loaded.
13:06:37 [INFO] [AdminCmd] 2281 alias loaded.
13:06:37 [INFO] [AdminCmd] 2 kits loaded.
13:06:37 [INFO] [AdminCmd] 20 banned players loaded.
13:06:39 [INFO] LWC: Latest version: 4.0.7
13:06:49 [INFO] [AdminCmd] Successfully linked with bPermissions.
13:06:51 [INFO] [LogBlockQuestioner] Loading LogBlockQuestioner v0.02.
13:06:51 [INFO] LogBlockQuestioner v0.02 enabled
13:06:51 [INFO] [Multiverse-Core] Loading Multiverse-Core v2.2-AB.
13:06:51 [INFO] [Multiverse-Core] - Version 2.2-AB (API v10) Enabled - By Rigby,
 fernferret, lithium3141 and main--
13:06:51 [INFO] [AllPay] - Version 3.0 - hooked into iConomy 6 for Multiverse-Co
re v2.2-AB
13:06:51 [INFO] [Multiverse-Core] Loading World & Settings - 'world_nether' - NE
THER with seed: 5622598517367492676
13:06:51 [INFO] Preparing start region for level 1 (Seed: 5622598517367492676)
13:06:52 [INFO] [Multiverse-Core] Loading World & Settings - 'skylands' - NORMAL
 with seed: 3930785930489239605 & Custom Generator: SkylandsPlus
13:06:52 [INFO] SkylandsPlus 0.9: Changed the world type of 'skylands' to flat (
this makes the void blue down to y = 0).
13:06:52 [INFO] Preparing start region for level 2 (Seed: 3930785930489239605)
13:06:52 [INFO] [Multiverse-Core] Loading World & Settings - 'world' - NORMAL wi
th seed: -8518214198097144373
13:06:52 [INFO] [bPermissions] Loading world: world
13:06:52 [INFO] Preparing start region for level 3 (Seed: -8518214198097144373)
13:06:53 [INFO] [Multiverse-Core] Loading World & Settings - 'survival' - NORMAL
 with seed: -581570235992305633
13:06:53 [INFO] Preparing start region for level 4 (Seed: -581570235992305633)
13:06:53 [INFO] [Multiverse-Core] Loading World & Settings - 'rpg' - NORMAL with
 seed: 1453038814264089876
13:06:53 [INFO] [Multiverse-Core] 5 - World(s) loaded.
13:06:53 [WARNING] [Multiverse-Core] Disabling MV's 'firstspawnoverride', since
spout doesn't handle new players well yet.
13:06:53 [WARNING] [Multiverse-Core] This means _new players_ may not spawn wher
e you've set your "mvspawn" AND
13:06:53 [WARNING] [Multiverse-Core] the config value 'firstspawnworld' will hav
e NO effect!!!
13:06:53 [WARNING] [Multiverse-Core] Talk to the Spout devs to get this fixed!
13:06:53 [WARNING] [Multiverse-Core]   --FernFerret
13:06:53 [INFO] [Multiverse-Core] Spout integration enabled.
13:06:53 [INFO] [Exp2Money] Loading Exp2Money v1.0.
13:06:53 [INFO] [Exp2Money] enabled!
13:06:53 [INFO] [MyHome] Loading MyHome v2.1b.
13:06:53 [INFO] [MyHome] 55 homes loaded
13:06:53 [INFO] [MyHome] Using localization: English (en_us)
13:06:53 [INFO] [MyHome] Access Control: Using bPermissions2.8.2
13:06:53 [WARNING] [MyHome] Help plugin not detected. Only providing help via /h
ome help.
13:06:53 [INFO] [MyHome] MyHome 2.1b enabled
13:06:53 [INFO] [MCDocs] Loading MCDocs v13.
13:06:53 [INFO] [MCDocs](Tazzernator/Andrew Tajsic) - v13 loaded.
13:06:53 [INFO] [dynmap] Loading dynmap v0.30.1-801.
13:06:53 [INFO] [Permissions] Loading Permissions v2.7.2.
13:06:53 [INFO] [AdminCmd] Successfully linked with Yeti's Permissions.
13:06:53 [INFO] [dynmap] Using Permissions 2.7.2 for access control
13:06:53 [INFO] [dynmap] Detected Spout
13:06:53 [INFO] [dynmap] Loaded 0 Spout custom blocks
13:06:54 [INFO] [dynmap] Loaded 14 shaders.
13:06:54 [INFO] [dynmap] Loaded 82 perspectives.
13:06:54 [INFO] [dynmap] Loaded 7 lightings.
13:06:54 [INFO] [dynmap] version 0.30.1-801 is enabled - core version 0.30.1-34
13:06:54 [INFO] [dynmap] Loaded 3 maps of world 'rpg'.
13:06:54 [INFO] [dynmap] Loaded 2 maps of world 'world_nether'.
13:06:54 [INFO] [dynmap] Loaded 3 maps of world 'skylands'.
13:06:54 [INFO] [dynmap] Loaded 3 maps of world 'world'.
13:06:54 [INFO] [dynmap] Loaded 3 maps of world 'survival'.
13:06:54 [INFO] [SimpleJail] Loading SimpleJail v1.7.4.
13:06:54 [INFO] [SimpleJail] ERROR: Could not find permissions plugin.
13:06:54 [INFO] [SimpleJail] Unloading SimpleJail v1.7.4.
13:06:54 [INFO] [SimpleJail] SimpleJail v1.7.4 disabled.
13:06:54 [INFO] [AntiGuest] Loading AntiGuest v2.5.0.
13:06:54 [INFO] [AntiGuest] Version 2.5.0 enabled
13:06:54 [INFO] [VoxelUpdate] Loading VoxelUpdate v1.0.13.
13:06:54 [INFO] [VoxelUpdate] VoxelUpdate version 1.0.13 loaded
13:06:54 [INFO] [iConomy] Loading iConomy v6.0.8b.
13:06:54 [INFO] [iConomy - Celty] Enabled (22 ms)
13:06:54 [INFO] [Vault][Economy] iConomy 6 hooked.
13:06:54 [INFO] [FalseBookIC] Loading FalseBookIC v0.91alpha.
13:06:55 [INFO] [ FalseBook IC ] FalseBookIC v0.91alpha by GeMo enabled
13:06:55 [INFO] [OpenInv] Loading OpenInv v1.7.3.
13:07:06 [INFO] [OpenInv] version 1.7.3 enabled!
13:07:06 [INFO] [DispNameChanger] Loading DispNameChanger v5.1.
13:07:06 [INFO] [DispNameChanger] English Translation Selected.
13:07:06 [INFO] [DispNameChanger] Spout detected! Using version 721.
13:07:06 [INFO] [DispNameChanger] Version 5.1 by [captainawesome7, itsatacoshop2
47, Daxiongmao87, Luke Zwekii, Sammy, SniperFodder] has been enabled.
13:07:06 [INFO] [FalseBookExtra] Loading FalseBookExtra v0.91alpha.
13:07:06 [INFO] [ FalseBook Extra ] FalseBookExtra v0.91alpha by GeMo enabled
13:07:06 [INFO] [NoCheat] Loading NoCheat v2.25.
13:07:07 [INFO] [NoCheat] version [2.25] is enabled.
13:07:07 [INFO] [FalseBookCore] Loading FalseBookCore v0.91alpha.
13:07:07 [INFO] [ FalseBook Core ] using Permissionsplugin Permissions!
13:07:07 [INFO] [ FalseBook Core ] FalseBookCore v0.91alpha by GeMo enabled!
13:07:07 [INFO] [MoneyDrop] Loading MoneyDrop v1.6.
13:07:07 [INFO] [MoneyDrop] Startup complete.
13:07:07 [INFO] [FalseBookCart] Loading FalseBookCart v0.91alpha.
13:07:07 [INFO] FalseBookCart v0.91alpha by GeMo enabled
13:07:07 [INFO] [WorldEdit] Loading WorldEdit v5.1.1.
13:07:07 [INFO] WorldEdit 5.1.1 enabled.
13:07:07 [INFO] WEPIF: Using the Bukkit Permissions API.
13:07:07 [INFO] WEPIF: Using the Bukkit Permissions API.
13:07:07 [INFO] [Multiverse-Portals] Loading Multiverse-Portals v2.2-AB.
13:07:07 [INFO] [Multiverse-Portals] - Version 2.2-AB Enabled - By Rigby and fer
nferret
13:07:07 [INFO] [Multiverse-Portals]  10 - Portals(s) loaded
13:07:07 [INFO] [Multiverse-Inventories] Loading Multiverse-Inventories v2.3-b7.

13:07:07 [INFO] [Multiverse-Inventories] Checking for conflicts in groups...
13:07:07 [INFO] [Multiverse-Inventories] No group conflicts found!
13:07:07 [INFO] [Multiverse-Inventories 2.3-b7] enabled.
13:07:07 [INFO] [VanishNoPacket] Loading VanishNoPacket v2.2.
13:07:07 [INFO] [VanishNoPacket] Now hooking into Dynmap
13:07:07 [INFO] [VanishNoPacket] v2.2 loaded.
13:07:07 [INFO] [Multiverse-NetherPortals] Loading Multiverse-NetherPortals v2.2
-AB.
13:07:07 [INFO] [MultiVerse-NetherPortals] - Version 2.2-AB Enabled - By Rigby a
nd fernferret
13:07:07 [INFO] [LogBlock] Loading LogBlock v1.50.
13:07:07 [INFO] [LogBlock] Permissions plugin found.
13:07:07 [INFO] [LogBlock] Scheduled consumer with bukkit scheduler.
13:07:07 [INFO] LogBlock v1.50 by DiddiZ enabled.
13:07:07 [INFO] [AdminCmd] Successfully linked with LogBlock
13:07:07 [INFO] [WorldGuard] Loading WorldGuard v5.4.
13:07:07 [INFO] WEPIF: Using the Bukkit Permissions API.
13:07:07 [INFO] WorldGuard: (rpg) Single session is enforced.
13:07:07 [INFO] WorldGuard: (rpg) TNT ignition is PERMITTED.
13:07:07 [INFO] WorldGuard: (rpg) Lighters are PERMITTED.
13:07:07 [INFO] WorldGuard: (rpg) Lava fire is blocked.
13:07:07 [INFO] WorldGuard: (rpg) All fire spread is disabled.
13:07:07 [INFO] WorldGuard: Loaded configuration for world 'rpg"
13:07:07 [INFO] WorldGuard: (world_nether) Single session is enforced.
13:07:07 [INFO] WorldGuard: (world_nether) TNT ignition is PERMITTED.
13:07:07 [INFO] WorldGuard: (world_nether) Lighters are PERMITTED.
13:07:07 [INFO] WorldGuard: (world_nether) Lava fire is blocked.
13:07:07 [INFO] WorldGuard: (world_nether) Fire spread is UNRESTRICTED.
13:07:07 [INFO] WorldGuard: Loaded configuration for world 'world_nether"
13:07:07 [INFO] WorldGuard: (skylands) Single session is enforced.
13:07:07 [INFO] WorldGuard: (skylands) TNT ignition is PERMITTED.
13:07:07 [INFO] WorldGuard: (skylands) Lighters are PERMITTED.
13:07:07 [INFO] WorldGuard: (skylands) Lava fire is blocked.
13:07:07 [INFO] WorldGuard: (skylands) All fire spread is disabled.
13:07:07 [INFO] WorldGuard: Loaded configuration for world 'skylands"
13:07:07 [INFO] WorldGuard: (world) Single session is enforced.
13:07:07 [INFO] WorldGuard: (world) TNT ignition is PERMITTED.
13:07:07 [INFO] WorldGuard: (world) Lighters are PERMITTED.
13:07:07 [INFO] WorldGuard: (world) Lava fire is blocked.
13:07:07 [INFO] WorldGuard: (world) All fire spread is disabled.
13:07:07 [INFO] WorldGuard: Loaded configuration for world 'world"
13:07:07 [INFO] WorldGuard: (survival) Single session is enforced.
13:07:07 [INFO] WorldGuard: (survival) TNT ignition is PERMITTED.
13:07:07 [INFO] WorldGuard: (survival) Lighters are PERMITTED.
13:07:07 [INFO] WorldGuard: (survival) Lava fire is PERMITTED.
13:07:07 [INFO] WorldGuard: (survival) Fire spread is UNRESTRICTED.
13:07:07 [INFO] WorldGuard: Loaded configuration for world 'survival"
13:07:07 [INFO] WorldGuard: 0 regions loaded for 'rpg'
13:07:07 [INFO] WorldGuard: 2 regions loaded for 'world_nether'
13:07:07 [INFO] WorldGuard: 1 regions loaded for 'skylands'
13:07:07 [INFO] WorldGuard: 15 regions loaded for 'world'
13:07:07 [INFO] WorldGuard: 0 regions loaded for 'survival'
13:07:07 [INFO] WorldGuard 5.4 enabled.
13:07:07 [INFO] [Dynmap-WorldGuard] Loading Dynmap-WorldGuard v0.13.
13:07:07 [INFO] [Dynmap-WorldGuard] initializing
13:07:07 [INFO] [Dynmap-WorldGuard] version 0.13 is activated
13:07:07 [INFO] [DeathTpPlus] Loading DeathTpPlus v3.8.0.1818.
13:07:07 [INFO] [DeathTpPlus] allow-wordtravel is: no
13:07:07 [INFO] [DeathTpPlus] Configuration v.3.4 loaded.
13:07:07 [INFO] [DeathTpPlus] Config is up to date
13:07:08 [WARNING] [DeathTpPlus] You are running on an newer CB Version
13:07:08 [WARNING] [DeathTpPlus] There might be issues, just letting you know
13:07:08 [INFO] [DeathTpPlus] 5 messages loaded for killstreak
13:07:08 [INFO] [DeathTpPlus] 5 messages loaded for deathstreak
13:07:08 [INFO] [DeathTpPlus] 7 messages loaded for multikill
13:07:08 [INFO] [DeathTpPlus] Loading death messages...
13:07:08 [INFO] [DeathTpPlus] 8 messages loaded for BLOCK_EXPLOSION
13:07:08 [INFO] [DeathTpPlus] 1 messages loaded for ENTITY_EXPLOSION
13:07:08 [INFO] [DeathTpPlus] 6 messages loaded for CAVE_SPIDER
13:07:08 [INFO] [DeathTpPlus] 9 messages loaded for CONTACT
13:07:08 [INFO] [DeathTpPlus] 7 messages loaded for CREEPER
13:07:08 [INFO] [DeathTpPlus] 11 messages loaded for DROWNING
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for ENDERMAN
13:07:08 [INFO] [DeathTpPlus] 13 messages loaded for FALL
13:07:08 [INFO] [DeathTpPlus] 9 messages loaded for FIRE
13:07:08 [INFO] [DeathTpPlus] 9 messages loaded for FIRE_TICK
13:07:08 [INFO] [DeathTpPlus] 5 messages loaded for GHAST
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for GIANT
13:07:08 [INFO] [DeathTpPlus] 8 messages loaded for LAVA
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for LIGHTNING
13:07:08 [INFO] [DeathTpPlus] 13 messages loaded for MONSTER
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for PIG_ZOMBIE
13:07:08 [INFO] [DeathTpPlus] 31 messages loaded for PVP
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for PVP_FISTS
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for PVP_TAMED
13:07:08 [INFO] [DeathTpPlus] 5 messages loaded for SILVERFISH
13:07:08 [INFO] [DeathTpPlus] 5 messages loaded for SKELETON
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for SLIME
13:07:08 [INFO] [DeathTpPlus] 5 messages loaded for SPIDER
13:07:08 [INFO] [DeathTpPlus] 4 messages loaded for STARVATION
13:07:08 [INFO] [DeathTpPlus] 4 messages loaded for SUFFOCATION
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for SUICIDE
13:07:08 [INFO] [DeathTpPlus] 13 messages loaded for UNKNOWN
13:07:08 [INFO] [DeathTpPlus] 1 messages loaded for VOID
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for WOLF
13:07:08 [INFO] [DeathTpPlus] 5 messages loaded for ZOMBIE
13:07:08 [INFO] [DeathTpPlus] 4 messages loaded for BLAZE
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for MAGMACUBE
13:07:08 [INFO] [DeathTpPlus] 4 messages loaded for ENDERDRAGON
13:07:08 [INFO] [DeathTpPlus] 4 messages loaded for DISPENSER
13:07:08 [INFO] [DeathTpPlus] 6 messages loaded for POISON
13:07:08 [INFO] [DeathTpPlus] 5 messages loaded for MAGIC
13:07:08 [INFO] [DeathTpPlus] Deathmessages v.3.4 loaded.
13:07:08 [INFO] [DeathTpPlus] Deathmessages are up to date
13:07:08 [INFO] [DeathTpPlus] Loading tomb messages..
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for BLOCK_EXPLOSION
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for ENTITY_EXPLOSION
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for CAVE_SPIDER
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for CONTACT
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for CREEPER
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for DROWNING
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for ENDERMAN
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for FALL
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for FIRE
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for FIRE_TICK
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for GHAST
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for GIANT
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for LAVA
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for LIGHTNING
13:07:08 [INFO] [DeathTpPlus] 1 messages loaded for PIG_ZOMBIE
13:07:08 [INFO] [DeathTpPlus] 1 messages loaded for PVP
13:07:08 [INFO] [DeathTpPlus] 1 messages loaded for SILVERFISH
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for SKELETON
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for SLIME
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for SPIDER
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for STARVATION
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for SUFFOCATION
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for SUICIDE
13:07:08 [INFO] [DeathTpPlus] 1 messages loaded for UNKNOWN
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for VOID
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for WOLF
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for ZOMBIE
13:07:08 [INFO] [DeathTpPlus] 2 messages loaded for BLAZE
13:07:08 [INFO] [DeathTpPlus] 4 messages loaded for MAGMACUBE
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for ENDERDRAGON
13:07:08 [INFO] [DeathTpPlus] 3 messages loaded for DISPENSER
13:07:08 [INFO] [DeathTpPlus] 4 messages loaded for POISON
13:07:08 [INFO] [DeathTpPlus] 4 messages loaded for MAGIC
13:07:08 [INFO] [DeathTpPlus] Tombmessages v.3.4 loaded.
13:07:08 [INFO] [DeathTpPlus] Tombmessages are up to date
13:07:08 [INFO] [DeathTpPlus] Found LWC (v4.0.7 (b613-git-754ca078))
13:07:08 [INFO] [DeathTpPlus] Successfully loaded 0 TombStones for world rpg
13:07:08 [INFO] [DeathTpPlus] Successfully loaded 0 TombStones for world world_n
ether
13:07:08 [INFO] [DeathTpPlus] Successfully loaded 0 TombStones for world skyland
s
13:07:08 [INFO] [DeathTpPlus] Successfully loaded 0 TombStones for world world
13:07:08 [INFO] [DeathTpPlus] Successfully loaded 0 TombStones for world surviva
l
13:07:08 [INFO] [DeathTpPlus] dtplist command registered
13:07:08 [INFO] [DeathTpPlus] dtpfind command registered
13:07:08 [INFO] [DeathTpPlus] dtptime command registered
13:07:08 [INFO] [DeathTpPlus] dtpreset command registered
13:07:08 [INFO] [DeathTpPlus] dtpadmin command registered
13:07:08 [INFO] [DeathTpPlus] deathtp command registered
13:07:08 [INFO] [DeathTpPlus] deaths command registered
13:07:08 [INFO] [DeathTpPlus] kills command registered
13:07:08 [INFO] [DeathTpPlus] streak command registered
13:07:08 [INFO] [DeathTpPlus] v3.8.0.1818 enabled
13:07:08 [INFO] [DeathTpPlus] Vault detected
13:07:08 [INFO] [DeathTpPlus] Checking ecnomony providers now!
13:07:08 [INFO] [DeathTpPlus] Economy provider found: iConomy 6
13:07:08 [INFO] [DeathTpPlus] Enabling DynMap Integration
13:07:08 [INFO] [DeathTpPlus] DynMap ready!
13:07:08 [INFO] [DeathTpPlus] initializing DynMap integration
13:07:08 [WARNING] [DeathTpPlus] You need to enable DeathTp to be able to use th
e DeathLocations Layer!
13:07:08 [INFO] [DeathTpPlus] Disabling DeathLocations Layer
13:07:08 [WARNING] [DeathTpPlus] You need to enable Tomb to be able to use the T
omb Layer!
13:07:08 [INFO] [DeathTpPlus] Disabling Tomb Layer
13:07:08 [INFO] [DeathTpPlus] DynMap Integration is activated
13:07:08 [INFO] Server permissions file permissions.yml is empty, ignoring it
13:07:08 [INFO] Done (32.225s)! For help, type "help" or "?"
13:07:08 [INFO] [ FalseBook Block ] 10 Areas loaded.
13:07:08 [INFO] [ FalseBook Block ] 0 Bridges successfully loaded.
13:07:08 [INFO] [ FalseBook Block ] 0 Doors successfully loaded.
13:07:08 [INFO] [ FalseBook Block ] 0 protected gateblocks successfully loaded.

**Comment by lexi-lambda** [comment]
As of the current version, this plugin requires PermissionsBukkit or PEX. You do not have either.
