### ISSUE TITLE
Request: bPermissions support?

### ISSUE THREAD

**Issue by DemmyDemon** [lexi-lambda/SimpleJail#5]
Hi!

Love SimpleJail a lot, and would very much appreciate it if you could implement bPermissions support.

Thank you!

**Comment by lexi-lambda** [comment]
Currently, while bPermissions is not supported natively, you can still use [Vault](http://dev.bukkit.org/server-mods/vault/) to allow SimpleJail to work with virtually any Permissions system, including bPermissions.
