### ISSUE TITLE
Unjail teleport point does not work.

### ISSUE THREAD

**Issue by Joroze** [lexi-lambda/SimpleJail#7]
I can't get Simplejail to work with the latest update you released. I'm on Bukkit 1.2.5 R4 and when I unjail someone now they don't get teleported to the unjail point, they go to the same jail point that they originally get sent to again..

Plugins: 
AntiCheat 
Backup
 BlockDisguise 
ChatManager
 ChestShop
 CommandBook 
creativecolours
 DisguiseCraft DrugMod
EasyEnchant 
iConomy
 Lockette
 LogBlock 
MobCatcher 
MineReset
 MobDisguisePVPControl 
Modifyworld
 OpenInv
 PaidRanks
 SimpleJail
 simplyvanish 
SuperpermsBridge
 TalkAs
 TreeAssist 
Vault
 VirtualChest
 WorldEdit
 worldguard-5.5.2

**Comment by lexi-lambda** [comment]
Fixed in version 2.0.3.
