### ISSUE TITLE
Prohibit Jailed Users from Using Certain Commands

### ISSUE THREAD

**Issue by ghost** [lexi-lambda/SimpleJail#8]
Hello,

I thought it would be pretty great for SimpleJail to be able to block jailed users from using certain commands. There are some commands on my server that don't require permission nodes (one of which being /spawn) and I love to have a command black/whitelist. Thank you!

**Comment by lexi-lambda** [comment]
Since SimpleJail works by changing jailed players' permissions groups, you can make sure that the jailed group doesn't have permissions to use the commands that would allow them to escape. You can tweak the permissions of the group to your needs.
